import "@/styles/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard with Ant Design",
  description: "Generated by create next app",
};
const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body>
      <AntdRegistry>
        {children}
      </AntdRegistry>
    </body>
  </html>
);

export default RootLayout;
